services:
  mongo-db:
    image: mongo:6.0.6
    restart: on-failure:3
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - ./docker/testing/mongo:/data/db
    ports:
      - 27017:27017
  postgres-db:
    image: postgres:16.3
    restart: on-failure:3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker/testing/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    